---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: httpd-frontend
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: httpd-frontend
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: httpd-frontend
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: JAVA_URL
          value: http://java-api:8080
        - name: PHP_URL
          value: http://php-api:8080/api.php
        image: harbor.lespaulstudioplus.info/library/httpd-frontend:latest
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: httpd-frontend
  name: httpd-frontend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: httpd-frontend
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpd-frontend
spec:
  routes:
  - services:
    - name: httpd-frontend
      port: 8080
    timeoutPolicy:
      idle: infinity
      response: infinity
  virtualhost:
    fqdn: demo.dev.jra.vcfdemo.com
    tls:
      secretName: tanzu-system-ingress/cnrs-default-tls
