---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: php-api
  name: php-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: php-api
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: php-api
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: my-release-mariadb
        - name: DB_USERNAME
          value: root
        - name: DB_NAME
          value: my_database
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: my-release-mariadb
        image: harbor.shared.dev.jra.vcfdemo.com/library/php-api@sha256:c2e75886e0095b09263985fd142d1098507c9b9b70007ff3984acd9c069cda39
        name: workload
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: php-api
  name: php-api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: php-api
